name: Test

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SOCKET_COUNT: 10

jobs:
  test:
    strategy:
      matrix:
        version: [18]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.version }}

      - run: node main.cjs
